os: Visual Studio 2017 

image:
- Visual Studio 2015
- Visual Studio 2017

platform:
  - x86
  - x64
  
configuration:
  - Debug
  - Release


build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

